### PR TITLE
Fix a typo

### PR DESCRIPTION
**Pull request by fvcr**
Fix a typo

### CODE REVIEW

**Comment by slegendr** [comment]
Thank you for the pull request. I am merging it into the parent repository for distribution in the next release. Could you please let me know the name and e-mail you would like entered into the project contributors file for attribution?

**Comment by fvcr** [comment]
Hello @slegendr,

Thanks for that.

Francisco Vilmar Cardoso Ruviaro <<francisco.ruviaro@riseup.net>>

**Comment by slegendr** [comment]
Hello @fvcr,
The merge to the parent repository has been completed. Thank you for correcting these typos.

**Review by tigerblue77 — APPROVED** [review]

**Comment by rhawalsh** [comment]
This has been incorporated for quite some time.  Thank you for the contribution, @fvcr .  I am closing this request.

**Pull request closed without merging**
