### PR TITLE
add loongarch64 support

### PR DESCRIPTION
**Pull request by Streamlethy**

### CODE REVIEW

**Comment by lorelei-sakai** [comment]
This project is primarily about recording and publishing particular versions of the VDO code, so we can't really accept pull requests here. However, I have adopted this change in the current development tree, which is available in the https://github.com/dm-vdo/vdo-devel project.

Thank you for the contribution!

**Comment by Streamlethy** [comment]
> This project is primarily about recording and publishing particular versions of the VDO code, so we can't really accept pull requests here. However, I have adopted this change in the current development tree, which is available in the https://github.com/dm-vdo/vdo-devel project.
> 
> Thank you for the contribution!

Thanks

**Comment by lorelei-sakai** [comment]
Since I merged these changed directly into the other repository directly, it doesn't have your name attached.

Would you like to be acknowledged in our contributors list, and if so, what name and e-mail address should I use?

**Comment by Streamlethy** [comment]
> Since I merged these changed directly into the other repository directly, it doesn't have your name attached.
> 
> Would you like to be acknowledged in our contributors list, and if so, what name and e-mail address should I use?

Yang Huang <huangyang@loongson.cn> 
Thanks a lot

**Pull request closed without merging**
