### PR TITLE
Correct the spec file to allow building on Fedora

### PR DESCRIPTION
**Pull request by hpvb**

### CODE REVIEW

**Comment by rhawalsh** [comment]
Hi @hpvb,

Thanks for providing this PR.  It's funny timing, because just as this came in, we had merged our own version of it ([that I already had on my fork](https://github.com/rhawalsh/vdo/commits/6.2.4.14-COPR/vdo.spec)) to our branches.  While I had been maintaining these updates on a fork, we realized that it was unnecessary to exclude them from the proper parent repository.

You should see the updates for this in our next push for the master branch.

**Comment by hpvb** [comment]
ha! could've saved myself some time :) thanks. I'll just close this.

**Comment by rhawalsh** [comment]
I apologize for the delayed response, I had meant to respond when I saw this originally but it was sufficiently buried in my mail that I am just getting to it.

**Comment by hpvb** [comment]
No problem at all! Sorry if my comment seemed salty. I meant it as it said. I was thanking you, and I'm glad I found out about your repository as perhaps I can get rid of my own COPR now :D

**Comment by rhawalsh** [comment]
Thanks.

Generally speaking, the rhawalsh/dm-vdo COPR is kept up to date with our latest push for our newest EL release (right now, that means EL8).  My fork contains all of the necessary changes to allow the current master branch to build on the supported releases of Fedora and Rawhide.

**Pull request closed without merging**
