### PR TITLE
Add riscv64 support

### PR DESCRIPTION
**Pull request by YukariChiba**
Add support for RISC-V 64 arch.

### CODE REVIEW

**Comment by lorelei-sakai** [comment]
This changes looks reasonable, but we're currently in the process of rearranging how this project is organized and this may not be the right branch to incorporate this. I'll try to follow up with a more definitive answer in a few days.

**Comment by lorelei-sakai** [comment]
Sorry for the long delay. We've decided that this project will serve a primarily archival purpose, so we can't really accept pull requests here. However, I have adopted this change in the current development tree, which is available in the https://github.com/dm-vdo/vdo-devel project.

Thank you for the contribution!

**Comment by lorelei-sakai** [comment]
Since I merged these changed directly into the other repository directly, it doesn't have your name attached.

Would you like to be acknowledged in our contributors list, and if so, what name and e-mail address should I use?

**Comment by YukariChiba** [comment]
> Since I merged these changed directly into the other repository directly, it doesn't have your name attached.
> 
> Would you like to be acknowledged in our contributors list, and if so, what name and e-mail address should I use?

Sure, thank you!

You can use `Yukari Chiba <i@0x7f.cc>` as my identity.

**Pull request closed without merging**
